window.onload = function() {
    var canvas = document.getElementById('canvas');
    var ctx = canvas.getContext('2d');
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(125, 250);
    ctx.quadraticCurveTo(100, 100, 250, 125);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(125, 250);
    ctx.quadraticCurveTo(140, 140, 250, 125);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(250, 125);
    ctx.quadraticCurveTo(400, 100, 375, 250);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(250, 125);
    ctx.quadraticCurveTo(360, 140, 375, 250);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(125, 250);
    ctx.quadraticCurveTo(100, 400, 250, 375);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(125, 250);
    ctx.quadraticCurveTo(140, 360, 250, 375);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(250, 375);
    ctx.quadraticCurveTo(400, 400, 375, 250);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(250, 375);
    ctx.quadraticCurveTo(360, 360, 375, 250);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(125, 250);
    ctx.lineTo(375, 250);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "pink";
    ctx.moveTo(125, 250);
    ctx.lineTo(375, 250);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "purple";
    ctx.moveTo(125, 250);
    ctx.lineTo(375, 250);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "purple";
    ctx.moveTo(250, 125);
    ctx.lineTo(250, 375);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 10;
    ctx.strokeStyle = "darkorange";
    ctx.moveTo(50, 450);
    ctx.lineTo(450, 50);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 10;
    ctx.strokeStyle = "darkorange";
    ctx.moveTo(450, 450);
    ctx.lineTo(50, 50);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 10;
    ctx.strokeStyle = "teal";
    ctx.moveTo(50, 50);
    ctx.quadraticCurveTo(250, 200, 450, 50);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 10;
    ctx.strokeStyle = "teal";
    ctx.moveTo(50, 450);
    ctx.quadraticCurveTo(250, 300, 450, 450);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 10;
    ctx.strokeStyle = "teal";
    ctx.moveTo(450, 50);
    ctx.quadraticCurveTo(300, 250, 450, 450);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 10;
    ctx.strokeStyle = "teal";
    ctx.moveTo(50, 50);
    ctx.quadraticCurveTo(200, 250, 50, 450);
    ctx.stroke();
    ctx.beginPath();
    ctx.lineWidth = 5;
    ctx.strokeStyle = "red";
    ctx.arc(250, 250, 75, 0 * Math.PI, 2 * Math.PI, false)
    ctx.stroke();
}